force-app/main/default/objects/Custom_Log__c/Custom_Log__c.object-meta.xml
<CustomObject>
    <description>Used to store all related to the migrations and batch proceses.</description>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>CL#{000000}</displayFormat>
        <label>Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
                <default>true</default>
                <label>Debug</label>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomLogHelper.cls
/**
 * @description Class to save information about migrations, batch classes, others
 */
public with sharing class CustomLogHelper {
    public static List<Custom_Log__c> stagedLogs = new List<Custom_Log__c>();

    private static String fixTitle(String title) {
        return title.length() > 100 ? title.substring(0, 100) : title;
    }

    public static void insertNewLog(String title) {
        insertNewLog(title, 'Debug');
    }

    public static void insertNewLog(String title, String level) {
        insertNewLog(title, level, null);
    }

    public static void insertNewLog(String title, String level, String className) {
        insertNewLog(title, level, className, null);
    }

    public static void insertNewLog(String title, String level, String className, String stackTrace) {
        insertNewLog(title, level, className, stackTrace, null);
    }

    public static void insertNewLog(String title, String level, String className, String stackTrace, String body) {
        insert new Custom_Log__c(
            Title__c = fixTitle(title),
            Level__c = level,
            Class__c = className,
            Body__c = body,
            Stack_Trace__c = stackTrace
        );
    }

    public static void stageNewLog(String title) {
        stageNewLog(title, 'Debug');
    }

    public static void stageNewLog(String title, String level) {
        stageNewLog(title, level, null);
    }

    public static void stageNewLog(String title, String level, String className) {
        stageNewLog(title, level, className, null);
    }

    public static void stageNewLog(String title, String level, String className, String stackTrace) {
        stageNewLog(title, level, className, stackTrace, null);
    }

    public static void stageNewLog(String title, String level, String className, String stackTrace, String body) {
        stagedLogs.add(
            new Custom_Log__c(
                Title__c = fixTitle(title),
                Level__c = level,
                Class__c = className,
                Body__c = body,
                Stack_Trace__c = stackTrace
            )
        );
    }

    public static void savePendingLogs() {
        upsert stagedLogs;
        stagedLogs = new List<Custom_Log__c>();
    }
}